// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.11
// source: pb/skoda.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Engine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Torque    int32 `protobuf:"varint,1,opt,name=torque,proto3" json:"torque,omitempty"`
	PowerInHP int32 `protobuf:"varint,2,opt,name=powerInHP,proto3" json:"powerInHP,omitempty"`
}

func (x *Engine) Reset() {
	*x = Engine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_skoda_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Engine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Engine) ProtoMessage() {}

func (x *Engine) ProtoReflect() protoreflect.Message {
	mi := &file_pb_skoda_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Engine.ProtoReflect.Descriptor instead.
func (*Engine) Descriptor() ([]byte, []int) {
	return file_pb_skoda_proto_rawDescGZIP(), []int{0}
}

func (x *Engine) GetTorque() int32 {
	if x != nil {
		return x.Torque
	}
	return 0
}

func (x *Engine) GetPowerInHP() int32 {
	if x != nil {
		return x.PowerInHP
	}
	return 0
}

type Skoda struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModelName      string  `protobuf:"bytes,1,opt,name=modelName,proto3" json:"modelName,omitempty"`
	CarEngine      *Engine `protobuf:"bytes,2,opt,name=carEngine,proto3" json:"carEngine,omitempty"`
	CarPriceInLacs int32   `protobuf:"varint,3,opt,name=carPriceInLacs,proto3" json:"carPriceInLacs,omitempty"`
}

func (x *Skoda) Reset() {
	*x = Skoda{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_skoda_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Skoda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skoda) ProtoMessage() {}

func (x *Skoda) ProtoReflect() protoreflect.Message {
	mi := &file_pb_skoda_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skoda.ProtoReflect.Descriptor instead.
func (*Skoda) Descriptor() ([]byte, []int) {
	return file_pb_skoda_proto_rawDescGZIP(), []int{1}
}

func (x *Skoda) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *Skoda) GetCarEngine() *Engine {
	if x != nil {
		return x.CarEngine
	}
	return nil
}

func (x *Skoda) GetCarPriceInLacs() int32 {
	if x != nil {
		return x.CarPriceInLacs
	}
	return 0
}

var File_pb_skoda_proto protoreflect.FileDescriptor

var file_pb_skoda_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x73, 0x6b, 0x6f, 0x64, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x63, 0x61, 0x72, 0x73, 0x22, 0x3e, 0x0a, 0x06, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x72, 0x71, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x74, 0x6f, 0x72, 0x71, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x77, 0x65,
	0x72, 0x49, 0x6e, 0x48, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x6f, 0x77,
	0x65, 0x72, 0x49, 0x6e, 0x48, 0x50, 0x22, 0x79, 0x0a, 0x05, 0x53, 0x6b, 0x6f, 0x64, 0x61, 0x12,
	0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a,
	0x09, 0x63, 0x61, 0x72, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x63, 0x61, 0x72, 0x73, 0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x09,
	0x63, 0x61, 0x72, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x61, 0x72,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x4c, 0x61, 0x63, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x63, 0x61, 0x72, 0x50, 0x72, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x4c, 0x61, 0x63,
	0x73, 0x42, 0x0f, 0x5a, 0x0d, 0x63, 0x61, 0x72, 0x73, 0x2f, 0x73, 0x6b, 0x6f, 0x64, 0x61, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_skoda_proto_rawDescOnce sync.Once
	file_pb_skoda_proto_rawDescData = file_pb_skoda_proto_rawDesc
)

func file_pb_skoda_proto_rawDescGZIP() []byte {
	file_pb_skoda_proto_rawDescOnce.Do(func() {
		file_pb_skoda_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_skoda_proto_rawDescData)
	})
	return file_pb_skoda_proto_rawDescData
}

var file_pb_skoda_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_skoda_proto_goTypes = []interface{}{
	(*Engine)(nil), // 0: cars.Engine
	(*Skoda)(nil),  // 1: cars.Skoda
}
var file_pb_skoda_proto_depIdxs = []int32{
	0, // 0: cars.Skoda.carEngine:type_name -> cars.Engine
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_skoda_proto_init() }
func file_pb_skoda_proto_init() {
	if File_pb_skoda_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_skoda_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Engine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_skoda_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Skoda); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_skoda_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_skoda_proto_goTypes,
		DependencyIndexes: file_pb_skoda_proto_depIdxs,
		MessageInfos:      file_pb_skoda_proto_msgTypes,
	}.Build()
	File_pb_skoda_proto = out.File
	file_pb_skoda_proto_rawDesc = nil
	file_pb_skoda_proto_goTypes = nil
	file_pb_skoda_proto_depIdxs = nil
}
